# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: authentication.gardener.cloud/v1alpha1
kind: OpenIDConnect
metadata:
  name: foo-bar
spec:
  issuerURL: https://some-identity-provider-abc.com
  clientID: foo-bar
  usernameClaim: example-claim-email
  usernamePrefix: "identity-abc:"
  groupsClaim: example-claim-groups
  groupsPrefix: "identity-abc:"