# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-shoot-oidc-service.config
  namespace: {{ .Release.Namespace }}	
data:
  config.yaml: |
    apiVersion: shoot-oidc-service.extensions.config.gardener.cloud/v1alpha1
    kind: Configuration
